# Authors:
#    - Claus Seibold <claus.seibold@ingenics-digital.com>
# 
# Copyright (c) 2024 Ingenics Digital GmbH
# 
# SPDX-License-Identifier: MIT
#

FROM python:3.9-slim AS base

ENV PIP_CACHE_DIR=/tmp/.pip_cache
ENV TOX_WORK_DIR="/tmp/.tox"

RUN apt-get update && apt-get install --no-install-recommends --yes \
    # Clean up
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir /host

RUN pip install --upgrade pip && pip install tox==4.15.0 tox-envlist==0.3.0 --no-cache-dir