name: CI-Testing

on:
  push:
    branches:
      - '*'
      - '*/*' # Match branches with single '/'


#            sudo apt install -y build-essential libsystemd-dev
jobs:
  lint:
    name: Check code for linting issues
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Linting
      run: |
          pip install --upgrade pip && pip install tox==4.15.0 --no-cache-dir
          pip3 install --user tox
          tox -e lint
  mypy:
    name: Check code for mypy issues
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Mypy
      run: |
          pip install --upgrade pip && pip install tox==4.15.0 --no-cache-dir
          pip3 install --user tox
          tox -e mypy
